spring.application.name=homesupportbackend

#Postgre SQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/homesupport_android
spring.datasource.username=postgres
spring.datasource.password=devloper


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true